eos/db/__init__.py
eos/db/saveddata/queries.py
gui/mainFrame.py
gui/utils/exportHtml.py
service/fit.py
service/port.py

I never liked the "in progress" animation for pyfa. It doesn't give you any information, and just doesn't look great. wxPython comes with a handy wx.ProgressDialog that can replace it.
Before (fit backup/import):
After (backup/HTML export):
After (importing):
waitDialog is still scattered around - most predominately while opening fits from previous pyfa session, but also when importing character and exporting skills needed (however these functions don't really take any time to do, so the wait dialog disappears so quickly). I am probably going to leave those in for now.
Need to test a bit more on Linux and OS X - from what I've tried it works great with importing multiple files and export as well, just need to thoroughly test.

Port custom wait dialog to wx.ProgressDialog

---

gui/builtinPreferenceViews/pyfaGeneralPreferences.py
gui/builtinViews/fittingView.py
gui/chromeTabs.py
service/fit.py

The current tooltips can be a bit irritating in some cases, eg. when using a tiling window manager which changes its layout when a tooltip appears. This branch fixes that for me by making the tooltips optional.

Make tab tooltips optional

---

eos/saveddata/fit.py

This addresses #261. Launchers do not have a "capacitorNeed" attribute (whilst projectile weapon systems do), so getModifiedItemAttr will return None rather than 0 when checking for cap-affecting modules. Adding an explicit check for None fixes the issue with the fit presented in the report.

Fix for #261

---

pyfa.py
service/fit.py
service/port.py

Support importing of fits exported from jEveAssets by implementing support for loading utf-16 XML.
Such XML is generated by software like jEveAssets's owned ships->fitting
export tool.
Without such detection, pyfa will go and try to import those as DNA
fits, with all the ensuing hilarity, thus the DNA import debug code as
well.

Support fits exported from jEveAssets

---

eos/capSim.py

Here's a possible fix for issue #211. I've tested it briefly, and it seems to make the capacitor estimation more sensible.
It changes the logic for staggering modules if they require ammo. Rather than simply dividing the cycle time by the number of modules (which doesn't account for the increased number of charges that can be used before reloading or the staggering of the reload times), it schedules each module separately, starting at different multiples of `stagger_amount`.
The `stagger_amount` I've chosen is a middle of the road approach. It spaces out the modules based mostly on cycle time but with reload time factored in as well. This works well for modules that spend a lot of their time reloading (like cap boosters with large charges). You'll get a decent distribution, without any of …

Fix stagger

---

gui/mainFrame.py

See issue #183 
Implemented functionality part of quickly fitting modules using shortcuts ALT+1-9.
ALT+1 automatically fits the first module in the market search list, ALT+2 the second, etc...
Implemented by defining new shortcuts similiar to existing ones and binding them to the imported ItemSelected event from marketbrowser.

Quickly fitting modules using ALT+1-9

---

gui/builtinStatsViews/resistancesViewFull.py

Implements #248 .
Calculate multiplier by diving EHP by HP and showing the result in a new line in the tooltip.

Showing Resist Multiplier in Tooltip

---

config.py

If started in a new installation savePath doesn't exist and crashes when the logging is configured.
I just moved the creation of savePath into a private method and used it before configuring logging.

Fix logging

---

eos/effectHandlerHelpers.py
gui/builtinContextMenus/__init__.py
gui/builtinContextMenus/metaSwap.py
service/fit.py

In the true spirit of open source - if you want a feature write it yourself.
This PR adds a right-click context menu (for modules) that brings up a list of meta-variations for the selected item(s). Selecting an item changes those modules to the selected meta-variation.
If multiple items are selected, menu only shows up if the variation list would be the same.
Saves a lot of clicking to meta-up or down a module to fit within skills or power budget etc.
I had a good look at the existing code, but I'm sure there are some style or architectural things you'll want me to fix.
(edit by blitzmann) Screenshot of how it looks:

Context menu to swap modules for different variation

---

gui/projectedView.py

Had a few people in corp not realise you could put a whole ship fitting in the 'Projected' view. Thought a basic usage hint might help.

Add a simple usage note to projected view

---

pyfa.py

Check that python-dateutil is installed at startup in pyfa.py, same way as for wxPython and SQLAlchemy (except for version check).

Check that python-dateutil is installed at startup

---

eos/graph/fitDps.py

Added a check for webs when graphing, where the effect is only applied if the target is within the web range. This should address #347.
This seems to do the job, giving me what I expect on the graph view with multiple webs in heated/unheated states, but I'd appreciate someone running over possible edge cases to confirm it works properly.
Test fits were variants of the following, with the webs in online, offline and heated states on different fits, graphed with settings ```{ distance: '0-100', velocity: 1000, angle: 90, signature: 100 }```.
```
[Moa, 347-TEST]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
Stasis Webifier II
Federation Navy Stasis Webifier
Tracking Computer II
Tracking Computer II
Tracking Computer II
250mm Railgun II, Caldari Navy Antimatter Charge M …
```

Fix for issue 347

---

eos/capSim.py

Modified capsim to deal with reload/clipSize logic before grouping modules for staggering. This prevents loaded AARs from being sent through as separate cap drain elements to other repairers of the same size.
Resolves #387

Fix for 387

---

eos/capSim.py

Modified capsim so that for non-capstable fits, the capacitor time will indicate the time at which the first module failed to activate due to insufficient capacitor rather than the time of the last successful activation.
Resolves #300

Fix for issue 300

---

eos/capSim.py
eos/saveddata/fit.py

Playing with the cap simulator, I noticed that turrets of the same type stack and have staggering applied when running through the cap simulator. This is not realistic behaviour as most (all?) pilots will
have grouped their turrets in-game, meaning they will all activate simultaneously rather than activating individually, offset from each other.
This change introduces a 'disable stagger' field to the drain tuple that is passed through to the cap simulator, allowing us to disable staggering on certain modules. This will enable us to add GUI options in the future to allow users to choose whether to stagger certain modules (eg, cap boosters, neuts) or have them all fire simultaneously. Currently this defaults to False (existing behavior) for all modules except for turrets, which will now …

Added option for disabling capacitor simulation staggering for certain modules

---

README.md

CREST support requires the requests module which may not be included by default in all users' distributions.

Add "requests" to README.md

---

gui/builtinPreferenceViews/pyfaGeneralPreferences.py
service/fit.py
service/port.py

@blitzmann this is in reference to #368 
Just starting this PR off as a discussion, by all means let me know if there's anything you don't like about it.
This defaults the preference to the current settings so it shouldn't affect anyone unless they opt out of it.
For my specific use-case: I don't want to export equipped charges because it usually conflicts with the cargo hold (e.g. I don't need 2x of the same type of script or 2x of the same crystal).
I'm usually loading different charges to see the stats on the right.
I've also gotten caught with cap boosters in the cargo hold + equipped going over the actual cargo hold limit.
Let me know what you think.

Make exporting charges a preference

---

config.py
gui/mainFrame.py
pyfa.py

*  Settable Window Title using commandline arguments
*  helps to distinguish between different instances
*  Settable savefile path using comandline arguments
* allows for multiple instances to not mix the fittings/characters
I personally needed these changes because I use pyfa to check hundreds of fits a day, and having them mixed with my personal fits was a pain! (Deleting even more after that confirmation box was introduced)

Added commandline arguments to specify window title and path for savefiles

---

service/fit.py
service/port.py

On import, modules will respect module quantity limits and hardpoints as well as activation limits.
Also minor bugfix to allow importing of XML loadouts via clipboard.
I only tested these with importing via clipboard, but they should work similarly for other styles. My test loadouts are here: https://gist.github.com/aacn500/e5ec75d4a2048506f4ae

Check that modules fit on imported fits #512 #522

---

gui/builtinContextMenus/changeAffectingSkills.py

The 'change affecting skills' context menu showed the same list of skills for both module and charge, despite modules and charges not being affected by the same skills. This change fetches the correct list of skills for charges instead.

Fix "Change charge skills" showing module skills #535

---

gui/builtinPreferenceViews/pyfaHTMLExportPreferences.py
gui/utils/exportHtml.py
service/settings.py

Recently I have seen some work on HTML Export tool here and wanted to contribute another improvement. I noticed a sizing issue while browsing fits on my laptop. Current online fitting viewer null-sec.com is not playing well with smaller screens so I decided to use another website called [Osmium](https://o.smium.org).
This commit adds an option to select preferred website while exporting fits. null-sec.com is the default option for compatibility but I suggest to swap them until null-sec fixes their page.

Added website selection for HTML Export

---

eos/graph/fitDps.py

In a January 2016 patch, the velocity of sentry drones seems to have been increased to non-zero values.
Checking if the velocity surpasses 1 m/s should correctly separate sentries from non-sentries now.
This should fix issue #511.

fix separation of moving/non-moving drones

---

service/port.py

Currently only "raw" DNA fitting string can be imported, e. g.: `11978:14146;1:14136;3:14240;3:18688;1:28744;1:3608;4:31366;1:31378;1:28201;4:2488;5:28668;1:28999;3:29001;3::`
The EVE ingame-browser uses `javascript:CCPEVE.showFitting('11978:14146;1:14136;3:14240;3:18688;1:28744;1:3608;4:31366;1:31378;1:28201;4:2488;5:28668;1:28999;3:29001;3::');` to show Fittings from DNA.
This patch allows Pyfa to handle these as well.

Import DNA fittings from ingame urls

---

gui/builtinPreferenceViews/pyfaHTMLExportPreferences.py
gui/utils/exportHtml.py
service/settings.py

Added an Opton in the HTMLExport menu to set the HTML export to produce
a minimal HTML version, without any styles or Javscript dependencies.
This can be useful if you are not javascript capable, or if you just
want to copy'n'pase the exported HTML into some web-editor (wordpress).
The generated HTML was tested in Eve and in a normal OOG browser, and it works. I ofcourse also tested the normal export , and that still works.

Added an option for HTML Export, to produce a minimal html version

---

config.py
gui/builtinViewColumns/misc.py

The RAH will use the damage profile applied to adjust the resist on the module.  You can see the adjusted resists in the module attributes.
This does **NOT** take into account the time it takes to adjust (it assumes it adjusts instantly).  It is unlikely there is a clean way to do this that is not needlessly complex, and I'm not sure it'd be that useful anyway for what we're doing.  (Run into the same problem with passive shield HP/s, for example.)

RAH follows damage profile

---

gui/mainMenuBar.py

Users are confused because they find the menu to edit attribute
overrides, change values, then do not see their values reflected.  There
is an option that needs to be enabled under the edit menu to show the
users overrides.
Moved this option from the edit menu to the window menu (next to the
existing attributes override editor), and grouped them together.
Functionality is not changed, merely placement of the overrides toggle.

Grouped Attributes override

---

gui/itemStats.py

Added a new column for the base (original) value.  Renamed column from "value" to "current value" to hopefully avoid confusion.
Also made the window a bit larger, since it's a bit small to fit everything.
Example of an item and a ship:
http://puu.sh/powiW/8837cc074e.png

Added base column to item window

---

gui/builtinViewColumns/misc.py

Gave it the RAH treatment. Now shows min/max values if it's a racial (since they have a strong/weak value), and only one for multi/burst (since it's omni).  Tooltip shows all four broken out.
Tried showing all 4 in the misc window, it gets kinda cluttered.  Showing min/max with all four broken out in the tooltip seems to be the best compromise.

Updated ECM to be more descriptive

---

eos/effects/shipbonusdreadnoughtrole1damagebonus.py

Used to be applied to Naglfar, but everyone knows that Vehement is the
new Naglfar, and never use projectiles after memorial day (only
hybrids).

Fixed type of weapon

---

eos/effects/adaptivearmorhardener.py

If there is no damage profile (likely from one that's deleted, and
somehow the profile doesn't get set back to uniform), then RAH tries to
apply null values.  This skips making the RAH reactive if that scenario
happens.
Also, RAH apparently fires on boosters (probably projected fits as well).

RAH gets pissy if there is no damage profile

---

eos/effects/energydestabilizationnew.py
eos/effects/energyneutralizerentity.py
eos/effects/energyneutralizerfalloff.py
eos/effects/energynosferatufalloff.py
eos/effects/energytransfer.py
eos/effects/entityenergyneutralizerfalloff.py
eos/effects/fighterabilityenergyneutralizer.py
eos/effects/remoteenergytransferfalloff.py
eos/saveddata/fit.py

Relevant code is in the effects file. Basically grabs the ships rig size, and applies the small/medium/large modifiers as a straight up percentage.
Example, ship on the left with the legacy code, ship on the right with the new code.
http://puu.sh/q4qsc/83975220d9.png
Todo:
*Could figure out how CCP handles unrigged ships (freighters, shuttles, pods).  This is an edge case, so we may simply choose not to cover it.
*Not sure how CCP determines the actual size, they may use a different formula than rig size.
*Need to handle the sig radius reduction for capital sized neuts. Still not sure on formula.
*Need to verify that stacking behavior works with cap batteries.  Assumption here is that the module size reduction applies without a stacking penalty and prior to the cap battery reduction.

Applied size reduction effect to neut/nos

---

README.md

```
Error: No available formula with the name "pyfa" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
This formula was found in a tap:
Caskroom/cask/pyfa
To install it, run:
brew install Caskroom/cask/pyfa
```

Update README.md with current brew instructions

---

gui/builtinViews/fittingView.py

```
Traceback (most recent call last):
File ".../Pyfa/gui/builtinViews/fittingView.py", line 463, in fitChanged
self.refresh(self.mods)
File ".../Pyfa/gui/builtinViews/fittingView.py", line 590, in refresh
self.SetItemBackgroundColour(i, self.slotColour(mod.slot))
File ".../Pyfa/gui/builtinViews/fittingView.py", line 560, in slotColour
return self.slotColourMap[slot] or self.GetBackgroundColour()
KeyError: 8
```

fixed exception that froze interface

---

gui/copySelectDialog.py
gui/mainFrame.py
service/fit.py
service/port.py

Hey, it's my first time working on Pyfa but I think I got what needed to be done for this.
I compared with the example in #726 and it matches.
Not sure about where to put the Multibuy option in the list so I just put it at the bottom, written MultiBuy (not sure about typography either).

Multibuy format export feature, adresses #726

---

eos/effects/minigamevirusstrengthbonus.py

Because integrated modules are a single module with both Data and Relic analizer built into one, ship hulls were giving a bonus twice over.
Changed it from adding the bonus for each individually (which worked fine when it was broken out) to simply adding it if either Hacking or Archaeology skill is present.

Integrated Hacking Modules Give Double Bonus Incorrectly

---

eos/effects/mining.py

This effect is only used by mining drones, and it's not been
implemented.
See #762 for more info

Mining Drones: Apply Mining Effect

---

gui/itemStats.py

Original method would only export values that were attached directly to the ship.  New method starts from the modified dict, which will export values without attribute IDs or original values.

Implement new method for exporting values

---

gui/builtinPreferenceViews/pyfaNetworkPreferences.py
service/network.py
service/settings.py

Related to issue #746 HTTP Proxy Username/Password
Briefly, changed 3 files:
- service/settings.py: add fields to store proxy login/pass in NetworkSettings class;
- service/network.py: use proxy login/pass info from NetworkSettings and prepend them to proxy address in form of login:password@host:port
- gui/builtinPreferenceViews/pyfaNetworkPreferences.py: GUI input fields to explicitly configure proxy login/pass
Now it looks like this:

Add login/password for proxy authorization in network settings

---

gui/builtinPreferenceViews/pyfaGeneralPreferences.py
gui/builtinViews/fittingView.py
service/fit.py

This is a new option for a pyfa behavior disturbing me since I started to use it: I have to press CTRL to open a fitting in a new tab - and I always mess it up...
With the option in "Preferences=> General" you can change the behavior to "Open fittings in a new page by default".
Every time you select a fitting, it will open a new page.
If the option is set, the behavior of CTRL is inverted and will open the fitting in the selected tab.
The option is set false by default.
I know it is no big thing, but as soon as you miss click, restore your fitting tabs the way you want needs a lot of clicks.

open fittings in new page by default

---

gui/shipBrowser.py

This will add trait tooltips to the shipbrowser.
-Category-View: no tooltips
-Ship-View: show trait as tooltip
-Fit-View&Search-View: show shiptype and trait as tooltip
the way how the browser handles the different items is "special" here and there but i think i finally got it.
Made a lot of crosstests to make sure the different stages are working fine.
Also, it was a request from @Sellec #786

Ship browser tooltip

---

eos/effects/mininginfomultiplier.py

Previously the mining crystal bonus was not applied to modules, so adding a crystal didn't change the amount mined at all.  This now applies.  Left the old application in place, so it still applies to a nonsense `specialtyMiningAmount` stat if you want to see that seperated out for some weird reason.

Applied Mining Crystal Bonus to modules

---

.gitignore

These don't exist for long, but could catch them in a commit if you clicked commit too quickly.

Ignore temp files

---

gui/builtinPreferenceViews/pyfaHTMLExportPreferences.py
gui/utils/exportHtml.py
service/settings.py

It seems like it would be a good idea to make this user configurable so they could enter whatever domain they want.
However with this entire HTML export feature being questionable, I didn't go that far. https://github.com/pyfa-org/Pyfa/issues/825
closes: https://github.com/pyfa-org/Pyfa/issues/826

Drops null-sec.com as an option

---

service/fit.py

#755 @Rylleyryelle said: 
> i as a user, would much prefer to have to DISABLE what i dont want running on them, rather than having to enable every stupid bleepity bleeping thing every time i change out a fighter to tinker.
- Adding Fighters: Activate all implemented abilities by default
-- Because you don't add deactivated modules to fittings, too
-- The usability of fighters is not optimal, so let's make it a little bit easier for the daily use.
- Adding Fighters: Deactivate fighter groups if more than the maximum number of active fighters are in bay (soft limit)
--It is still possible to activate more fighter then allowed for testing, switching fighters, etc...

Activate fighter standard attack and limit active fighters

---

gui/itemStats.py

See: https://puu.sh/swp4e/058450d696.gif
You can pass in either the column number or the attribute name to sort on.  We attempt to handle it cleanly, and default back to no sorting if something goes wrong.
The sort parameter is not required, so anything else using it won't break.
We don't handle reverse sorts (clicking on the column header twice) and for `reasons` sometimes it sorts up and sometimes it sorts down.  Most likely has to do with different types, but not terribly worried about it.
Also, since Name and Price aren't part of the `attrs` array we can't sort on those.  If you click on those columns, it doesn't sort at all, to prevent various issues.
@blitzmann this is ready to be merged.

Add ability to sort compare list

---

eos/effects/subsystembonusamarrdefensive2remotearmorrepairamount.py
eos/effects/subsystembonuscaldaridefensive2remoteshieldtransporteramount.py
eos/effects/subsystembonusgallentedefensive2remotearmorrepairamount.py
eos/effects/subsystembonusminmatardefensive2remoteshieldtransporteramount.py

Moved the 4 remote rep subsystem effect bonuses to calculate early in the engine.  This correctly calculates these bonuses for effects, previously these effect bonuses wouldn't be calculated until after projection calcs ran.

Subsystems calculate after projection calcs

---

service/port.py

Drones can and often are in different stacks due to bandwidth and skills. The DNA would mess up in these cases because they would include duplicate ids with different numbers.
This commit groups the drones by the itemID before generating the DNA.
closes: https://github.com/pyfa-org/Pyfa/issues/367

Groups drones before generating DNA

---

eos/effects/usemissiles.py

Bomb effects can now be projected.
For calculations that include a cycle time (cap warfare bombs), the cycle time assumes that you launch a bomb as soon as the cooldown is complete (`moduleReactivationDelay`).

Handle Lockbreaker, Void, and Focused Void Bombs

---

requirements.txt
requirements_test.txt

Caught most of the main ones, I think.
(Yes I'm sneaking EVE-Gnosis in here, just so I don't have a conflict when I submit the cap/shield sim fix)

Requirements for Pyfa

---

gui/marketBrowser.py

There is a lot of logic that overwrites the user's choices of meta filtering on every search.
That's a little too clever. Especially if the user is looking for different variations of a certain meta.
If a user wants to include the other meta buttons they can re-add them after filtering.
closes: https://github.com/pyfa-org/Pyfa/issues/818

Remembers user's meta filtering choices

---

service/character.py

Now checks to make sure that the skill we're trying to import exists, and that the level being set is between (or equal to) 0 and 5.
We also now output more logging data, previously errors were simply printed to the console, which being a threaded process wouldn't show in the main console and end users would never see the error.
If a skill that is being imported isn't in our list (generated based on the All 5 character), or the skill level is out of range, we simple log an error and continue on.
Hopefully helps with issues like #928
@blitzmann this is ready to be merged.

Add some sanity checks and validation of imported character data

---

eos/db/saveddata/databaseRepair.py
eos/db/saveddata/queries.py
service/prefetch.py

This addresses three issues:
1. Character skills exist for a character that doesn't.  See #917
2. Damage pattern on a fit is set to a damage pattern that doesn't exist.  See #777
3. Character on a fit is set to a character that doesn't exist. (Can't find which issue mentioned this.)
@blitzmann I know that you wanted to avoid running database validation and cleanup each time, but I don't think it's avoidable.  We are running into scenarios where people can't even launch Pyfa, so they can't get to a point when they _could_ click a button to fix it.
And yes, I know that the first two issues won't cause that scenario.  But since a lot of users won't ever take the time to post here or on the forums about it (just rage quit and go to another tool), I think that this is the best approach.
Plus, …

Database Validation and Cleanup

---

eos/effects/skillremoteecmdurationbonus.py

Change to use skill rather than group, and modify correct attribute.
Another ECM burst bug that's been this way for years.  I swear, no one uses these things.
Thanks to saeka for reporting the bug.
@blitzmann this is ready to be merged.

ECM Burst Projectors effect

---

config.py
gui/bitmapLoader.py
gui/graphFrame.py
gui/itemStats.py
service/pycrest/eve.py
service/settings.py

See #854 for history.
@blitzmann if you want to keep the original PR you should be able to cherry pick the second commit on this one.
This has been tested (on Windows) against: 
- `Téléchargements` works
- `הורדות` (Hebrew) - pyCharm itself chokes on this one. Pyfa doesn't like it either: 
`Missing icon file: C:\Users\Ebag333\Documents\GitHub\Ebag333\??????\imgs\gui\pyfa.png`
For testing the one that seems to break most reliably is the cert path, so you can simply drop the check in `config` from:
```
if isFrozen():
certName = "cacert.pem"
os.environ["REQUESTS_CA_BUNDLE"] = getPyfaPath(certName).encode('utf8')
os.environ["SSL_CERT_FILE"] = getPyfaPath(certName).encode('utf8')
```
This may be helpful:
https://docs.python.org/2/library/codecs.html

Unicode Paths 2: The Reckoning

---

gui/builtinStatsViews/miningyieldViewFull.py
gui/builtinViewColumns/misc.py

From #790 
>Linking https://www.reddit.com/r/Eve/comments/5o2npc/miner_qol_improvement_m3s_calculated_inclient_on/ where people disagree that m3/h is useful.
>Now that EVE has m3/s, it probably makes sense to revert this and stick with what EVE represents.
Since no one can agree whether /s or /h is better, why not have both?
Reverts the default display back to /s since that's what CCP has added and is shown in the client.
Moves /h into tooltips, so you can quickly see the /h rate if that's what you prefer.
If @blitzmann doesn't mind, can add a second line to the mining yield stats pane to add /h to be displayed below the /s.  So we'd effectively have both displayed in the GUI (without having to go to the tooltip).
Also, fixed the tooltips for the Mining Yield stats pane, so it shows …

Revert back to /s for mining. Adds /hour to tooltips.

---

eos/saveddata/fit.py

```
Comparing databases:
1106372 -> 1111328
Renamed items:
"Korranis DNA": "Korrani's DNA",
"Drezins DNA": "Drezin's DNA",
"Naval Capsuleer Enlistment (Amarr)": "Enlistment (Amarr) for Naval Capsuleers",
"Naval Capsuleer Enlistment (Caldari)": "Enlistment (Caldari) for Naval Capsuleers",
"Naval Capsuleer Enlistment (Gallente)": "Enlistment (Gallente) for Naval Capsuleers",
"Naval Capsuleer Enlistment (Minmatar)": "Enlistment (Minmatar) for Naval Capsuleers",
"Naval Capsuleer Blueprint Documents": "Blueprint Documents for Naval Capsuleers",
[+] - new item
[-] - removed item
[*] - changed item
(x => y) - group changes
[+] - effect or attribute has been added to item
[-] - effect or attribute has been removed from item
[y] - effect is implemented
[n] - effect is not implemented
Items:
[-] QA …
```

Update database to 1111328

---

eos/db/saveddata/databaseRepair.py
service/prefetch.py

See #949 for history.
Catches both null and empty names.  Sets name to `Unknown` if found.

Catch scenario where Damage Profile and Target Resist names are missing

---

eos/db/saveddata/databaseRepair.py
service/prefetch.py

See #954 for some history.
Here's an example output from cleaning up a very large and very old database.
```
2017-01-27 13:36:46,260 eos.db.saveddata.databaseRepair DEBUG    Running database cleanup for orphaned drones items.
2017-01-27 13:36:46,306 eos.db.saveddata.databaseRepair ERROR    Database corruption found. Cleaning up 21 records.
2017-01-27 13:36:46,315 eos.db.saveddata.databaseRepair DEBUG    Running database cleanup for orphaned cargo items.
2017-01-27 13:36:46,357 eos.db.saveddata.databaseRepair ERROR    Database corruption found. Cleaning up 3 records.
2017-01-27 13:36:46,358 eos.db.saveddata.databaseRepair DEBUG    Running database cleanup for orphaned fighters items.
2017-01-27 13:36:46,362 eos.db.saveddata.databaseRepair DEBUG    Running database cleanup for orphaned …
```

Orphaned item cleanup

---

eos/gamedata.py
eos/modifiedAttributeDict.py
gui/builtinViewColumns/misc.py

Adds the ability to show info for capacitor boosters and remote ancil armor/shield reppers, in addition to the existing local ancil armor/shield reppers.
shows the reload time to make it more clear the span that the total amount of reps lasts.
Added to tooltip the number of charges used, and the amount of time for 5, 10, and 25 cycles of the booster (1 cycle is using all charges + reload time).
A picture is worth a thousand words, so this gif is probably a small novel.
https://puu.sh/tEU9L/bd88811fc9.gif
See #959 for history.

Add extra info for misc column for fueled boosters (cap, shield, and armor)

---

gui/graphFrame.py

Moves import to top of file.
Adds better handling for 2.0.
@blitzmann I know you were playing around with this a bit, did you get the string issues sorted?
Also, I know you say that this takes forever to import, but at least with 2.0 this isn't an issue.  I didn't see a huge speed increase by not importing it.
With it setup this way, the graph window opens *VERY* fast.  In current build (prior to the last pre-release build) it opens painfully slow.  So I think a combination of the import fixes and 2.0 helps a lot with that.
This is _not_ ready to be merged (doesn't handle versions properly).

Matplotlib 2.0 support

---

gui/droneView.py
service/fit.py

Check if we have active drones when merging, if we do make them all active to avoid getting weird scenarios (like deactivating stacks, or only activating parts of stacks).  Fixes #728

Merging Drone Stacks

---

gui/graphFrame.py

Change matplotlib to be imported at the top and not use the import hack.  Slows down the startup times slightly, but much simpler.

Matplotlib Import Fix

---

eos/mathUtils.py
tests/test_modules/eos/test_mathUtils.py
tests/test_modules/gui/test_aboutData.py
tests/test_modules/service/test_attribute.py
tests/test_package.py

Just a quick little PR to add a few tests for Pyfa.
Also, found a small bug in `floorFloat`.  We were handling it a bit hacky for 2.6 compataibility, and this meant we would round the wrong way for negative values (-1.1 rounded to -1, when it should round to -2).  Didn't see any use cases when we'd hit that, but rewrote it anyway to use `floor` since we're  not supporting 2.6 anymore, and it's MUCH simpler.

Tests for Pyfa

---

gui/itemStats.py

Just a quick little dev QoL.
Adds a pane that exposes properties on an item, so we don't have to set breakpoints just to see what that one @property from `modules.py` set.
Need to check where we're  pulling this from, I think there's a better spot.
https://puu.sh/uiAOR/a316d5a05f.png

Add Properties Pane

---

eos/config.py
eos/effects/tractorbeamcan.py
eos/modifiedAttributeDict.py
gui/builtinStatsViews/capacitorViewFull.py
gui/itemStats.py
gui/mainFrame.py
service/fit.py
service/port.py
service/settings.py

Just a small add to have a tooltip for capacitor neut resistance.  A very useful stat, but one not exposed at all effectively.
https://puu.sh/uykft/0076290861.gif
Also prevents exceptions from modifiedAttributeDict when getting an attribute that doesn't exist (returns default).  (Ran into this when passing in an object that doesn't exist because we're on a blank tab.)
Bit of Tox cleanup.

Tooltip for capacitor neut resistance

---

service/settings.py

There are times when `s` is not None with the `get()` (when the settings have already been accessed). Having an `else: s = None` at the end of that condition will cause errors (for example, ran into this when opening prefs window). Was introduced with the `pytest` merge.

Fix settings provider

---

service/fit.py

Quick fix for an issue with a log statement when changing active fighter count

Fix an exception caused by too few variables for string formatting

---

gui/builtinViewColumns/state.py
gui/commandView.py

Simple QoL improvement / a fix for a regression dating back to November.
Bit of background: I disabled the state column for the Command / Fleet view when we made the change over to the new command burst mechanics. The reason behind this is because the State column, which controls which image is show to represent state of item, only received `stuff`. Normally we check what `stuff` is, and figure out what to do from there (eg: if `stuff` is a module, check the modules state and display an image that works).
The problem originally with command fits is that it shares the same `stuff` type as projected fits. So there wasn't a way to differentiate a projected fit from a command fit in the State class.
But holy shit, this was super easy after taking a look at it again tonight. We can't …

Re-introduce Command Fit State

---

eos/saveddata/fit.py

Break project application code out of main item iteration, and apply it after command boosts have been applied to the fit.
I do want to take another peak at it in a few days to see if there's any fat we can trim with that code now being in it's own block (for example review the items that are chained to see if there's anything unnecessary that's currently being run for projections, such as character, that I didn't bother to put brain cycles towards tonight). But for now this seems to fix the issue and works well.

Fix for #1081

---

gui/builtinContextMenus/metaSwap.py
service/fit.py

When using variations context menu, selecting an implant would remove it and then add the new one. The problem here was that `recalc=Fasle` was set when adding the new one, and thus the fit did not recalculate with the new implants.
This quick fix simply sets that recalc flag to `True`. To prevent double recalc, I added a `recalc` parameter to `removeImplant()` and set that to `False`.

Fix for #1090

---

gui/builtinPreferenceViews/pyfaHTMLExportPreferences.py
gui/builtinViews/fittingView.py
service/settings.py

Does what it says. From time to time we get report of random crashes that kill the process, which 8/10 times is related to the automatic HTML export. It has been known for a while that this can cause issues, and so we just need to kill that particular feature.

Remove auto html

---

gui/builtinContextMenus/metaSwap.py
service/fit.py

This should be a quick QoL and performance improvement, easy win. In the same light as #1094, this adds recalc flags to the add/remove fit service functions for drones, fighters, and boosters to prevent a double recalc when switching the modules. This does not include #1094 (didn't merge master into dev yet, but it'll get in there eventually).

Variation menu efficiencies 

---

eos/saveddata/module.py

This is a quick fix for #1096 - adds a check in `Module.fits()` to make sure we aren't trying to put a cap module on a sub cap ship.

Restrict cap modules to only cap ships

---

eos/db/migrations/upgrade22.py
eos/db/saveddata/booster.py
eos/db/saveddata/cargo.py
eos/db/saveddata/character.py
eos/db/saveddata/crest.py
eos/db/saveddata/damagePattern.py
eos/db/saveddata/drone.py
eos/db/saveddata/fighter.py
eos/db/saveddata/fit.py
eos/db/saveddata/implant.py
eos/db/saveddata/implantSet.py
eos/db/saveddata/module.py
eos/db/saveddata/override.py
eos/db/saveddata/skill.py
eos/db/saveddata/targetResists.py

As discussed in #961. Preliminary testing shows this works well for existing and new databases. It's completely transparent to the user, and not something that is exposed at the moment (but we could later on if deemed necessary).
The primary motivation for this addition was to help with troubleshooting. If a user sends us a database file, having the times in which modules are added / modified, it's one more data point available to us to help piece together what happened. It also allows for some nifty things in the future (recently modified fits, for instance).
Three things to note:
- DATETIME is apparently a data type in SQLite, even though I continuously read that it isn't. This is the way SQLAlchemy creates it with it's own `DateType` class, but creating a table or column with that as …

Create and Modify fields for most database tables

---

eos/db/__init__.py
eos/gamedata.py
eos/saveddata/price.py
gui/boosterView.py
gui/builtinContextMenus/priceClear.py
gui/builtinPreferenceViews/pyfaGeneralPreferences.py
gui/builtinPreferenceViews/pyfaStatViewPreferences.py
gui/builtinStatsViews/__init__.py
gui/builtinStatsViews/priceViewMinimal.py
gui/builtinViewColumns/price.py
gui/implantView.py
gui/itemStats.py
gui/statsView.py
service/market.py
service/price.py

The main highlights:
- Removes the market price cache, and instead we append our price object to all items.  Now the item itself is the cache.
- Move the price thread to the price service. Makes more sense.
- Clean up a bunch of the logic
- Remove unused functions, and merge functions where possible.
- Make a number of things more object oriented (no taking a list of objects to get a list of IDs just to convert back to objects).
- Adds a new full pricing pane that breaks down value more discretely.
https://puu.sh/uJ07t/5aabdf3e4a.png
- Move the old pricing pane to a minimal version, so folks can still use that if they so desire.
- Adds pricing column to implants/boosters, because why not? Fixes #678
Unlike the prior PR (#1038), this leaves the thread handling intact.  We rework it a …

Pricing Refactor

---

config.py
service/settings.py

Rewrite/continuation of #1080.
I made the requested changes. And there are more to come.
For instance, on Linux systems, applications user data should be stored in `$XDG_DATA_HOME` which should default to ` ~/.local/share/[app-name]` if the variable is not set. See [here for details](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).
In addition, I would like to be able to move the `imgs` directory to `/usr/share` as well, `$XDG_DATA_DIRS` eventually. When I'm talking about moving, I mean being able to run Pyfa as it is meant to be now and add the possibility to run it with the `imgs` directory in this new path.
I've been trying to reproduce the issue with `os.path.join` and unicode strings. And the only error I have is with this:
```python …
```

Allow system wide installation

---

service/price.py

Trying to manipulate and save objects from one thread in another will cause sqlalchemy session exceptions. This brings it back to the original method of modifying the price object in another thread, but committing it in the main thread, avoiding the issues.
Will have to look for a better way later (not really supposed to share session objects at all with other threads), but this should work in the interim. 
Should resolve #1151, #1148, #1146, #1145

Do not commit price objects to database from within thread

---

gui/builtinViews/fittingView.py
service/fit.py

Lots of little issues that have built up over the years that were previously hidden due to silent errors (dragging blank module somewhere, dragging module from market to T3D Mode, dragging charge from cargo to module not working, etc). Tested as many combinations as I could think of, seems to work better now. Need to implement a better way to handle these things in the future, but for now this fixes things.
Possible fix for #1186

Fix a bunch of item swapping mechanisms

---

gui/builtinContextMenus/priceOptions.py
gui/builtinStatsViews/priceViewFull.py
gui/builtinStatsViews/priceViewMinimal.py
gui/contextMenu.py
service/settings.py

I have gone with the context menu solution to set options.
I have a list of labels in the ContextMenu definition, but I'm not sure this is the right way/right place. I put it there to always have the list in the same order.
I haven't used the bitmask thing yet but I could, as you wish.
The full pane looks self-explaining to me, but the minimal could benefit from a breakdown in a tooltip.
I also grouped price options as they were grouped in the pane (implants are grouped with boosters).

Pricing pane 1158

---

gui/boosterView.py
gui/builtinViews/fittingView.py
gui/cargoView.py
gui/commandView.py
gui/droneView.py
gui/fighterView.py
gui/marketBrowser.py
gui/projectedView.py
gui/utils/staticHelpers.py

This patch addresses #1149 
I believe that wx 3.x for newer Mac operating systems has a memory buffer error allowing garbage data to be passed around through wx gui event handlers, resulting in a critical error that makes the Mac client unusable without a restart
I shortcut this problem by avoiding the wx-provided event handler data variable by using a simple python static variable, and apply the fix where I could find similarly implemented DragAndDrop events
I will note that this implementation is both quick and dirty, as my goal here was to influence the code base as little as possible. So I even leave in a conditional check `if self.GetData():` which is a call to a inherited wx function, because I did not want to make any assumptions about what this code was actually doing.
Therefore, …

updated drag and drop behavior to not trigger a suspected wx bug on Mac

---

eos/saveddata/fit.py

The problem was the fact that pyfa didn't `clear()` previous results, so it calculated values on top of already calculated values. I have a feeling this was also broken in previous releases since command fits weren't included in the `clear()` like projected fits were (though I haven't tested that theory), and the new fit calculated flag probably made the problem more apparent.
Speaking of `clear()`, we no longer `clear()` projected and command fits in the base `clear()` for hopes of performance boosts. If Fit B projects onto Fit A, and we change Fit A, we shouldn't have to clear (and thus recalculate) Fit B - values under that fitting should remain static until either it has changed, or something that it depends on has changed (via `__resetDependentCalcs()`).
This seems to work in the …

Fix for #1193 - compounded bonuses during recursive command / projected fittings

---

config.py
eos/db/saveddata/queries.py
service/fit.py

Also includes a fix for our commits. When a commit dies for whatever reason, catch the exception, rollback the session, and then raise the exception again so that the user knows something happened. However, rolling back the session allows pyfa to continue on working for things that aren't broke (whereas if we didn't rollback, any session manipulation would be hindered by session errors)

Fix issue with fit deletion

---

eos/effects/subsystembonusminmatardefensive2localrepheat.py
eos/effects/subsystembonusminmataroffensive1hmlhamvelo.py
eos/effects/subsystembonusminmataroffensive3missileexpvelo.py

Fix effects for loki subsystems:
- defensive subsystem "Adaptive Defense Node" should apply overheat bonus to both shield and armor repair amount bonus
- offensive subsystem "Launcher Efficiency Configuration" should apply missile velocity and missile explosion velocity bonuses to charge instead of launcher.

Fix loki effects

---

gui/builtinContextMenus/metaSwap.py

https://github.com/pyfa-org/Pyfa/issues/1261
Added logic to condition statement in metaSwap.py to accommodate cargoItem context. Will replace existing cargo item with selected item and retain the original stack amount.
Seems like a fairly useful feature and I didn't realize how much I wanted it until I read the ticket. Tested on Windows 7, unable to test on any other platforms.
Screenshot:

Issue #1261 show variations menu for cargo items

---

gui/builtinStatsViews/miningyieldViewFull.py
gui/statsPane.py

Changes to statsPane.py:
Added new method applyBinding which loops through all the children
of the contentPanel passed to it and binds contextHandler to each of them
Changes to miningyieldViewFull.py:
Call to new method applyBinding
---
#1241  
It looks like the child elements were never having any binding applied to them so I have created a new method to do this. 
There still appears to be an issue with the miningyieldViewFull panel displaying the context menu for firepowerViewFull but I believe that this is because binding occurs on the panel at load time when statsPane.py runs for all of the views. We would probably need something to remove the binding from this panel when it is toggled onto.
I'm not really an expert though, what do you think @blitzmann ?
I have built and tested this …

Issue #1241 Bind contextHandler to children of contentPanel

---

eos/effects/boostermissilevelocitypenalty.py

Changes to boostermissilevelocitypenalty.py:
Get booster attribute value using booster.getModifiedItemAttr()
before attempting to apply it to avoid type error
---
#1280 
Previously we were not getting the booster attribute value and were instead attempting to apply to the attribute name as the value, which was causing a type error.
I have built and tested this fix on Windows 7 but don't have access to test on any other platforms.

Convert booster attribute to value before applying

---

gui/characterEditor.py

Change to characterEditor.py:
Added logic to prevent a crash when attempting to execute
self.PopupMenu(menu) when menu was False. This would occur in the
situation where there were no saved implant sets.
---
#1264 
Fixed a scenario where spawnMenu in characterEditor.py was attempting to create a list of implant sets even when the list of implant sets contained no items which resulted in a crash. 
The new behavior if there are no implant sets is to do nothing. I've put a trace in there but that might be unnecessary and could be removed.
I have built and tested this fix on Windows 7 but don't have access to test on any other platforms.

Issue #1264 Don't attempt PopupMenu if getMenu returned False

---

gui/characterSelection.py

Changes to characterSelection.py:
grantMissingSkills now uses _buildSkillsTooltipCondensed to
generate a list of skills to update
_buildSkillsTooltipCondensed now outputs level and ID rather than
just level so that it can be used by grantMissingSkills
Anything else using _buildSkillsTooltipCondensed like exportSkills
and fitChanged have been amended to extract just the level from
the skills map rather than level and ID
---
#1289 
Granting missing skills (without strict skills set) now always provides the pre-requisite skills because _buildSkillsTooltipCondensed is used to generate the skills map (which contains the requirement skills). This does not appear to have any performance impact compared to the master version which only applied the top level skills and I couldn't really think of …

Change how skillsMap is generated

---

eos/effects/shipbonustitang2alldamagebonus.py

Addresses erroneous thermal damage double-dipping for Komodo titan as outlined in [#1332](https://github.com/pyfa-org/Pyfa/issues/1332).

[fix] eos - remove Komodo thermalDamage double-dipping

---

service/port.py

Change to service/port.py to include Slot.SERVICE in export
Also fixes a crash when attempting to export citadel with service
modules to CREST
--
#1362 
Service slots were not being included in EFT or CREST exports. This was causing a crash in the case of exporting a citadel with service modules. Example exports after change, EFT:
```
[Athanor, Athanor fit]
Standup Ballistic Control System I
Standup Stasis Webifier I
Standup Warp Scrambler I
Standup Target Painter I
Standup ASML Missile Launcher I, Standup ASML-LD Missile
Standup Heavy Energy Neutralizer I
Standup Heavy Energy Neutralizer I
[Empty Rig slot]
[Empty Rig slot]
[Empty Rig slot]
Standup Cloning Center I
Standup Cloning Center I
[Empty Service slot]
```
CREST:
`{"items": [{"flag": 11, "type": {"href": …

Include service modules in EFT export

---

eos/effects/energynosferatufalloff.py

When calculating the capactitor need of an energy nosferatu the
amount was being modified incorrectly by the energy warfare
resistance of the ship. Change to only apply energy warfare
resitance modifier if this is a projected effect.
---
#1360 
When fixing #1322 I introduced a new bug that caused the capacitor need of nosferatus to be modified by the energy warfare resistance of the ship. The correct approach is to only modify this amount in the case where this is a projected effect.

Remove energy warfare resistance on capNeed calc

---

gui/graphFrame.py

This is a partial reversion of d4df989 which seems required for the graphFrame to unbind event handlers.

Ensure graph frame unbinds its event handlers.

---

eos/capSim.py
eos/saveddata/fit.py

This allows the module attribute reloadtime to be passed to the capsim. This addresses #1490. Without reload preference true, this capsim, sims exactly the same as previously. With reload preference true the capsim is only different for fits with modules that have a reload other than 10secs.

CapSim changes to make reloadtime a variable.

---

eos/effects/doomsdaybeamdot.py
eos/effects/doomsdayconedot.py
eos/effects/doomsdayhog.py
eos/effects/doomsdayslash.py
eos/effects/microjumpportaldrive.py

Partially resolves #1484. We still have the following modules that use cap but have no active state.
Jump Portal Generators.
Cargo Scanners
Ship Scanners
Survey Scanners
Passive Targeters

Create basic effects files for various modules.

---

eos/saveddata/fit.py

This fixes the reported sustainable tank for AAR and ASB. Resolves #1439 when used with the new capsim.
I did this fix in eso/savedata/fit.py. You can do it in effects but that involves overwriting the peak (reinforced) repair figures which I think should be shown all the time as the actual peak. If extrattributes were put in to hold sustained values then you could do the fix in effects without any down side.
Anyway have a play and see if it breaks. Comment welcome.

Respect 'Factor in Reload' preference for sustainable tank (tidied up).

---

gui/builtinItemStatsViews/itemAttributes.py
gui/builtinItemStatsViews/itemCompare.py
gui/builtinItemStatsViews/itemEffects.py
gui/builtinItemStatsViews/itemProperties.py
gui/display.py

@blitzmann and I discussed this over Slack and replacing usage of `sys.maxsize` (which varies by system bitness) with this was the conclusion.

Use list control length instead of sys.maxsize for platform compatibility

---

eos/saveddata/fit.py

This addresses Issue 1511. Where it wasn't taken into
account that logistic drones dont use cap too, like
Ancilliary Shield Boosters. And was triggering code
for them.

Fix new sustained reps code for logistic drones.

---

service/esiAccess.py
service/network.py
service/settings.py

Requests session objects already can use proxies for all requests it makes. Just need to provide them to session object

Use proxies from Pyfa's "Network settings" for ESI requests

---

gui/builtinItemStatsViews/itemDescription.py
gui/builtinItemStatsViews/itemTraits.py

Popup menu with "Copy" command (can work more reliable that shortcuts sometimes)
Select all on Ctrl+A
Copy to clipboard on Ctrl+C
If nothing is selected, whole text is copied.
Fixes #1529

Copy text from item traits and desription panels

---

eos/saveddata/character.py

For #1599 , When API Refresh is pressed and clearSkills on the character is called in the Update thread, also clear dirty skills.

Remove asterisk next to character name after API refresh

---

gui/utils/exportHtml.py

#1637 
---
The HTML export now contains an EFT block rather than an Osmium ship DNA link. I have had to make a new level to contain the EFT block, because otherwise all of the EFT blocks for fittings in the same ship type would be displayed together (which sucks if you have 50 Vexor fits like me).
I was going to add a copy to clipboard button but I'm not very good at Javascript and it looks like more than just a one liner. Since this is pretty much an end of life feature I don't think it's really that important but I might look into it in the future.

HTML export now contains EFT block

---

gui/esiFittings.py

This will catch errors that happen on init of StoppableHttpServer, such as in Issue #1627, and display helpful prompt that suggests trying manual server settings. This is probably a bit too broad of a catch, but hopefully some tracebacks get posted to help sift through the noise

Adds exception handler for when HttpServer fails on init

---

gui/builtinItemStatsViews/itemMutator.py

#1597 
---
Added new methods for resetting and randomizing the attributes of an Abyssal item. Two new methods resetMutatedValues() and randomMutatedValues are included in itemMutator.py
It's randomly generating uniformly distributed floats at the moment, but it can easily be changed to ints if needed.

Added reset and randomize buttons to mutaplasmid view

---

gui/itemStats.py

Fix for #1657
Due to 47016c6 closeEvent no longer directly deletes the window.
Instead we should have the button fire a wx.CloseEvent via wx.Window.Close.
This will cause event.Skip() to actually close the window when called via ItemStatsDialog's CloseEvent bind.

Make itemStats.closeBtn fire a wx.CloseEvent

---

eos/gamedata.py

Fix for #1659 
I assume the second argument is a typo given the use case.
If not giving it a default value also works.

Typo fix for eos.gamedata.translations["Boolean"]

---

eos/effects/skillbonusdronedurability.py
eos/effects/skillbonusdroneinterfacing.py
eos/effects/skillbonusdronenavigation.py
eos/effects/skillbonusdronesharpshooting.py

This should provide a fix for #1662 and allow similar drone implants to function without additional changes.
I tested the Bumblebee implant in game found it does impact fighters.
Given the descriptions only mention drones not fighters CCP may change that as a bug fix.
For now however the effects are applied to fighters to match actual gameplay.

Allow drone skill effects to process implants

---

eos/effects/shipdronescoutthermaldamagegf2.py

The required skill should be Light Drone Operation as light drones don't require Drone Avionics.
This causes the damage bonus to apply correctly. Thus giving a max skill Hobgoblin II 29.7dps rather than 19.8dps.

Fixes the Helios's drone damage bonus.

---

eos/saveddata/booster.py
eos/saveddata/fighter.py
eos/saveddata/fit.py

This should cover everything currently not copied when using the copy button.
Specifically it should now copy booster side effects, fighter abilities and command fits along with the active state for fighters, projected fits and command fits.

Added missing data to fit copying

---

gui/bitmap_loader.py

Fix for #1673 
This will cause attempts to get non-existent icons via BitmapLoader.getStaticBitmap to return a question mark icon (0.png) rather than fail. This is effectively the same behavior seen under the attributes tab already.
This specific issue was caused by the 'Capacitor Warfare Resistance Bonus' having no icon.
There's a blank space in place of the icon when hovering over an Abyssal Cap Battery in game.

Have missing icons display as question mark icons

---

service/port.py

Desired behavior for #1684
Should cause fit implants to always be used if present for file and clipboard imports.

Have imported fits always use implants if present

---

service/market.py

Fix for #1683 
Cause of the bug:
service.market.marketGroupHasTypesCheck is used to check if a market group has items and by extension if it has child market groups. 
If ITEMS_FORCEDMARKETGROUP contains a market group's ID then marketGroupHasTypesCheck will return true.
gui.builtinMarketBrowser.marketTree.expandLookup assumes groups with items cannot contain child groups.
Thus the hard coded marketGroupIDs corresponding to the 'Booster' group caused it's children to be ignored after changes by CCP moved boosters to child market groups based on slot and type.
Changes:
Updated booster IDs for ITEMS_FORCEDMARKETGROUP and removed entries that already have identical marketGroupIDs in the database.
Updated getVariationsByItems to correctly handle boosters for the new market groups. Note the …

Update market.service to reflect new booster market groups.

---

gui/builtinContextMenus/moduleAmmoPicker.py

Fixed missile module ammo picker not showing damage type icons.

---

service/port/efs.py

port.efs should no longer use anything from FitDeprecated.
To more easily test for issues the data export now also rounds it's output to 6 decimal places.
This PR also contains the changes from #1754.
I don't expect the format to require any additional changes before release.

EFS export update for pyfa 2.5

---

service/port/efs.py

#1755 was merged with the development branch in October but never made it to master branch.  
It looks like it's been forgotten so this patch adds the missing changes along with minor linting.  
I've also changed the SpoolOptions to always fully spool up regardless of settings.  
"damageMultiplierBonusMax" and "damageMultiplierBonusPerCycle" are exported already but they can only calculate the spool if the export is consistent and doesn't change with user settings.

Merge missing changes from #1755, efs version bump and minor linting.

---

service/port/efs.py

Ignores the spool up for now since EFS ignores it for repairs anyway.

Adds Mutadaptive Remote Armor Repairers to EFS exports.

---

service/port/port.py

This PR addresses #1835 for mutated items split on  `\n` or `\r`  before parsing.

Mac Osx clipboard can store items with \r, ensure we split on newline or carriage return

---

eos/gamedata.py

Adds checks to make sure effects return correct `isImplemented` and `isType` values when they are called before handler generation.

Additional fix for #1902

---

gui/mainMenuBar.py

#1871 
---
- Added some logic to enable and disable the undo and redo buttons depending on the contents of the command history as follows:
- Disable both buttons if no commands in the history
- Disable undo if there are commands in the history, but the current command is not (this means we are already at the beginning)
- Disable redo if there are commands in the history, and the current command is the most recent (we are at the end)
- Otherwise undo and redo are enabled

Logic to enable/disable redo/undo buttons

---

README.md

Do to the situation in Gentoo where there is still no wxpython-4 ebuild I had to look for another solution. Luckily there is an ebuild from a third-party available but that will probably never make it upstream as it is because it still needs a lot of work and none of the original package maintainers seem interested in doing it. Even the pull requests for the dependencies are moving very slowly. But it works for Pyfa and that is enough for me to be able to make a working Pyfa ebuild again.
So for now I created this overlay which should probably be easier to keep updated to deliver the most recent Pyfa versions and all required dependencies for Gentoo users.
I will also try to get this registered so it can be easily installed with the "layman" tool and keep the install instructions updated …

Add link to Gentoo pyfa overlay

---

gui/esiFittings.py

On my machine, using the ESI import feature and clicking "Fetch Fits" gives the appearance of nothing happening. Turns out, this was because by default the tree on the left-hand side of the window has zero width by default and the parent window needs to be resized to see the fits. Fix this by setting a minimum size for the fitting browser tree and increase the default window size to compensate.

improve sizing on esi fit import browser

---

config.py
gui/bitmap_loader.py

This commit reenables the ability to load the images from a zip file instead of a directory structure. It is possible to set the location of this file via configforced.py
This possibility was partly present at one time but was commented out and not really ported to python3. I maintain this patch in the Gentoo overlay since I package the images into a zip. It would be great if we could upstream this functionality but no hard feelings if this isn't something you want :wink:  .

Support loading images from zip

---

gui/characterEditor.py

This adds the ability to set the level of a skill by pressing a number key, e.g. pressing 1 will set the skill's level to 1, and so on. I didn't add a way to "unlearn" a skill via a shortcut, but I can easily make it respond to `Delete` or something else.
I've never used wxPython before, so sorry if using a custom event isn't the best way to achieve it.

Add keyboard shortcuts to character level editor

---

gui/builtinAdditionPanes/implantView.py
gui/builtinContextMenus/__init__.py
gui/builtinContextMenus/implantSetAdd.py
gui/builtinContextMenus/implantSetLoad.py
gui/builtinViews/entityEditor.py
gui/mainFrame.py
gui/setEditor.py

Did two things:
- Added new menu "Add As New Implant Set". After entering the name for the set (and checked that such name is not used), implant set editor is opened with focus on the new set.
- Renamed "Add implant set" to "Load Implant Set" for consistency.

Issue #2073: Added ability to add a list of implants from implant view to a new implant set

---

gui/builtinAdditionPanes/fighterView.py

a fit with fighters can trigger this exception. e.g. this Chimera [fit](https://wiki.eveuniversity.org/Chimera/Fittings) from EvE University Wiki

i18n_db: fix ValueError exception when name should be groupName

---

.travis.yml
gui/shipBrowser.py
locale/zh_CN/LC_MESSAGES/lang.po
service/market.py

I think it's best practice to follow official translation, so sorting `msgid`s won't really affect these translations.
On a side note: i18n_db is getting big, please consider to merge it early and solve issues in separate commit / PR.

i18n_db: sort and (slightly) update zh_CN translation

---

gui/chrome_tabs.py

When switching fit tabs, _TabRenderer.InitTab is called a whopping 140 times, making tab-switching annoyingly slow.
This reduces the number of these calls to merely 6, and switching is much faster now (although still not instantaneous, as I'd like)

Ignore _TabRenderer.SetSize when new size is the same as old size

---

gui/mainFrame.py

From the comment on that line, it looks like it was a workaround for some bug.
It seems to work fine without it on Mac OS X. Would appreciate testing on Linux/Windows.

Do not sleep for half a second in OpenFitsThread.run()

---

gui/chrome_tabs.py

It was doing it once via `self.Parent.SetSelection(sel_tab)` and then directly itself.

_TabsContainer.CheckTabSelected no longer posts PageChanged event twice

---

eos/saveddata/fit.py
eos/utils/stats.py
gui/builtinContextMenus/itemRemove.py
gui/builtinStatsViews/capacitorViewFull.py
gui/builtinStatsViews/firepowerViewFull.py
gui/builtinStatsViews/outgoingViewFull.py
gui/builtinStatsViews/outgoingViewMinimal.py
gui/builtinStatsViews/targetingMiscViewMinimal.py
locale/README.md
locale/lang.pot

This time I went for tool tip strings :). These changes also include a named placeholder for Russian translation.

I18n: more string annotations (mostly tooltips)

---

eos/saveddata/targetProfile.py

2020/08/12 Eve Online Patch increased Em Resists for some npc in the group of  'Retaliating Caldari Entities'
The groups target profile has been recalculated and edited.

Updated 'Retaliating Caldari Entities' target profile

---

gui/builtinStatsViews/targetingMiscViewMinimal.py

####################
Traceback (most recent call last):
File "gui\statsPane.py", line 79, in fitChanged
File "gui\builtinStatsViews\targetingMiscViewMinimal.py", line 218, in refreshPanel
AttributeError: 'str' object has no attribute 'foramt'

Fix typo in ECM targetting view

---

eos/saveddata/module.py
service/port/efs.py

ADD: Added the ability for EFS exports to contain the following information: shieldrecharge rate, inertia, energy|neutraliser Resistance
I am building my own EFS and it is struggling as it can't simulate cap warfare/shield recharge or apply dps properly without.

Adding more information to EFS Export

---

service/esiAccess.py

Due to unexpected ESI SSO breakage by adding an "aud" claim, skip
validation of the claim. If in the future CCP specifies which "aud"
claim to verify against, this can be changed to pass the appropriate
"audience" value.
Fixes #2421

Skip validation of JWT "aud" claim

---

service/port/efs.py

FIX: Added check to correct add the burst jammer's burst radius
https://github.com/pyfa-org/Pyfa/issues/2450

Issue 2450 : ECM Burst Jammers burst range is 0 when exported to EFS

---

README.md

Both the Travis CI and Slack links are dead, so I replaced it with the Appveyor CI.

Replace dead README badges with current CI badge

---

gui/builtinShipBrowser/fitItem.py

Copying out of the buffer containing the fit object inside of the draw function causes infinite redraws on macos, moved the functionality outside of the draw function itself 
Tested on M1 mac on Ventura/Sonoma and Windows

fix infinite redraws on macos

---

service/settings.py

It's possible an `http://` url string set for the `https` proxy, and the code can't strip it.

fix proxy proto string strip

---

gui/builtinItemStatsViews/helpers.py

WxWidgets in theory respects system-level dark modes, and most of the components behave in a sane way by default. `listmix.ListRowHighlighter` however mixes SYS_COLOUR_LISTBOX with SYS_COLOUR_HIGHLIGHT, which has a very different effect with dark system colors resulting in half of the rows being illegible with the intended white font. This change manually overrides ListRowHighlighter's highlight colour with a lightened SYS_COLOUR_LISTBOX when in dark mode.
Before:
After:

Improve AutoListCtrl legibility in dark mode

---

service/port/muta.py
service/port/xml.py

Currently, when exporting in XML format, the mutation information is lost, and when reimporting the file, Pyfa will simply ignore the mutated item, leaving an empty slot.
This PR implements writing/using mutation info when exporting/importing in XML format.
For mutated items (modules and drones), write and read these `hardware` tag attributes:
- `base_type`, specifying the name of the base type.
- `mutaplasmid`, specifying the name of the mutaplasmid.
- `mutated_attrs`, specifying the mutated attributes and their values, in the format of EFT export, e.g. `capacitorNeed 108.0, cpu 34.4`.

Add mutation info to XML export/import.

---

gui/builtinMarketBrowser/events.py
gui/builtinMarketBrowser/itemView.py
gui/builtinMarketBrowser/marketTree.py
gui/marketBrowser.py

This pull requests adds a new entry in the market browser tree below "Recently Used Modules": "Charges for Active Fit".
It lists all charges that can be fitted to a module of the currently open fit tab. It can be used to e.g. quickly creat the needed cargo items. It is inspired by the similiar ingame ghost fitting feature.
I added a new entry, which needs a translation btw, with the same icon as "damage pattern". Benchmarks of the feature resulted in unconclusive results, the calculation of the needed modules took between 2 and 30ms on my machine. Updating the list might be the bottleneck, but I am not sure how it is implemented.
Happy for any feedback, first python / pyfa pull request in a while.

Add "Charges For Active Fit" market tree shortcut

---

gui/builtinShipBrowser/pfListPane.py
gui/utils/gdi.py

This closes 
https://github.com/pyfa-org/Pyfa/issues/2121
https://github.com/pyfa-org/Pyfa/issues/2261
https://github.com/pyfa-org/Pyfa/issues/2225

Fix wxWidget crash caused by GDI object limit
