pyfa-org/Pyfa

eos/saveddata/fit.py

fix issue copying fits with sqlalchemy 1.0

---

gui/builtinViewColumns/misc.py

Hi,
noticed that some stuff has been broken in the last patch, so gave a try at fixing them.
First issue: CCP renamed some of the groups in the database, so neuts, nos and tracking
disruptors were not displaying correctly anymore. This fixes that (simple name change).
Second issue: new guidance disruptors use a new set of attributes, this is now displayed
correctly in the miscellaneous column. (However, could maybe be more useful, e.g.
instead of computing missile velocity + flight time penalty, give combined range
penalty?)
I've included a screenshot of the change
Current:
The fix:
Hope it's useful. Love Pyfa by the way, I've found really useful.

Fixed display of neut and nos amount, and guidance disruptors

---

gui/mainMenuBar.py

@blitzmann 
OSX uses "Command-," for application preferences

Use idiomatic osx preferences shortcut

---

service/port.py

When looping through items on the fit, subsystems are added immediately but modules are added to a list to be added in a subsequent loop. Tested and seems to work for EFT, XML, DNA and CREST formats, but I'm not certain on EftCfg.

Fix importing T3 cruisers #556

---

eos/graph/fitDps.py

And added a quick formula for module falloff and applied it to Target Painters and Heavy Grapplers.

Fixed ewar on damage graphs, 

---

eos/effects/modulebonusdronedamageamplifier.py

Fixing the issue by adding `, stackingPenalties=True` to the end of the lines.

Fixing Drone Damage Amplifier fighter stacking issue #576

---

eos/effects/missileaoecloudsizebonusonline.py
eos/effects/missileaoevelocitybonusonline.py
eos/effects/missileexplosiondelaybonusonline.py
eos/effects/missilevelocitybonusonline.py
eos/effects/pointdefense.py
eos/effects/remoteguidancedisruptfalloff.py
eos/effects/structureMissileGuidanceEnhancer.py
eos/effects/structureballisticcontrolsystem.py
eos/effects/structureenergyneutralizerfalloff.py
eos/effects/structuremoduleeffectecm.py
eos/effects/structuremoduleeffectremotesensordampener.py
eos/effects/structuremoduleeffectstasiswebifier.py
eos/effects/structuremoduleeffecttargetpainter.py
eos/effects/structuremoduleeffectweapondisruption.py
eos/effects/structurewarpscrambleblockmwdwithnpceffect.py

Effect files for citadel modules added

Added effects files

---

service/port.py

Fix for #760. Applies on all tech level of laser turrets and ammo, not only T2.

Fix of the number of charges in multibuy

---

eos/effects/fighterabilityevasivemaneuvers.py
eos/effects/modulebonusnetworkedsensorarray.py
eos/effects/modulebonusomnidirectionaltrackinglinkoverload.py
eos/saveddata/fighter.py
eos/saveddata/fighterAbility.py
eos/saveddata/ship.py
service/character.py

* Omnidirectional Tracking Link overheat applies to explosion radius/velocity bonuses.
* Networked Sensor Array affects fighters' sensor strengths.
* Long range heavy fighters no longer appear to require Bomb Deployment.
* Carriers and supercarriers are no longer capped at 300km lock range.
* Fixed superiority fighters' main attack and the ammo count for limited abilities.
* Added the Evasive Maneuvers ability to superiority fighters.
* Made fighter DPS calculations more accurate when factoring reload time. It now realizes that all abilities stop while reloading, instead of just the ones with charges.

Fixed a few fighter/carrier bugs:

---

eos/effects/miningdroneoperationminingamountbonuspostpercentminingdroneamountpercentchar.py

See https://github.com/pyfa-org/Pyfa/issues/762 for full details.  This fixes issue 1

Removed stacking penalty from Mining Drone Rigs

---

gui/itemStats.py

Allows for exporting a CSV file out of the Items tab.

Add button for exports

---

eos/saveddata/fit.py
scripts/jsonToSql.py
scripts/prep_data.py

Lets this run in 32 bit python.

Limit lanaguage from multi to en-us

---

gui/shipBrowser.py

Merry Christmas @Ebag333 :)
Solve #803
New item in shipbrowser context menu `Set as 'Projected' to selected fitting`

Add "projected" to selected fitting via shipbrowser right click menu

---

eos/db/migrations/upgrade16.py
eos/db/saveddata/fit.py
eos/saveddata/fit.py
gui/additionsPane.py
gui/notesView.py

This allows users to save text notes for each fit. They may do this for history, or usage, etc.
Closes #364

Adds a new notes pane for each fit

---

eos/db/saveddata/booster.py
eos/effects/boosterarmorhppenalty.py
eos/effects/boosterarmorrepairamountpenalty.py
eos/effects/boostercapacitorcapacitypenalty.py
eos/effects/boostermaxvelocitypenalty.py
eos/effects/boostermissileexplosioncloudpenaltyfixed.py
eos/effects/boostermissileexplosionvelocitypenalty.py
eos/effects/boostermissilevelocitypenalty.py
eos/effects/boostershieldcapacitypenalty.py
eos/effects/boosterturretfalloffpenalty.py
eos/effects/boosterturretoptimalrangepenalty.py
eos/effects/boosterturrettrackingpenalty.py
eos/gamedata.py
eos/saveddata/booster.py
eos/saveddata/character.py
eos/saveddata/drone.py
eos/saveddata/fighter.py
eos/saveddata/fit.py
eos/saveddata/implant.py
eos/saveddata/mode.py
eos/saveddata/module.py
eos/saveddata/ship.py
eos/types.py
gui/itemStats.py

Seems it's just easier to create a new PR.

Effect toggle (rebased)

---

eos/effects/industrialcoreeffect2.py

Industrial core for Rorq

---

eos/effects/miningdroneoperationminingamountbonuspostpercentminingdroneamountpercentchar.py

Fixes erroneously applying amount bonus to Ice Harvesters.
Removes unnecessary skill level flag.

Fix Mining Rig Effect for Ice Harvesters

---

eos/effects/industrialcommandshipskilllevelmultiplierics3.py
eos/effects/industrialcommandshipskilllevelmultiplierics4.py
eos/effects/industrialcommandshipskilllevelmultiplierics5.py
eos/effects/orecapitalshipskillmultiplier5.py

These 4 effects break processing, because the bonus gets set to 0.  This causes nothing to happen in the effect, so it looks like it isn't working.

Remove Effects

---

gui/builtinStatsViews/miningyieldViewFull.py
gui/builtinViewColumns/misc.py

A little improvement for our mining guys.
Miners usually calculate their mining yield per hour.

Mining Yield "per hour". 

---

gui/builtinViewColumns/misc.py

See #879 
@blitzmann this is ready to merge.

Fix tooltip order for ECM

---

eos/saveddata/fighter.py
service/port.py

Fighter Support added for
- importDNA
- importEFT
- importEFTCfg
- importXML
- exportDNA
- exportXML
Solves #800 
I added a new property `fighterSquadronMaxSize`.
`amountActive `has the same value by default but is different as soon as the number of fighters set.

Fighters for export and import functions

---

eos/effects/structureenergyneutralizerfalloff.py
eos/saveddata/fit.py

When adding Neuts to an Engeneering-Complex you get the error that "float" has no attribute xx..
It seems like "container" was not passed by accident, as indicated by the firstline-comment that it was not used previously.
HTH

fixed parameters in call when adding neuts to structures.

---

eos/effects/adaptivearmorhardener.py
eos/effects/elitebonuscommanddestroyerinfohidden1.py
eos/effects/elitebonuslogisticremotearmorrepairoptimalfalloff1.py
eos/effects/rolebonusremotearmorrepairoptimalfalloff.py
eos/effects/shipbonusforceauxiliarya4warfarelinksbonus.py
eos/saveddata/fit.py
gui/utils/exportHtml.py
pyfa.py
tox.ini

Removes a few exceptions.
Increases line length.  As of now all lines adhere to 165 chars or less (default is around 120).
Add comments for why we have some exceptions, as several should be removed down the road once more refactoring is done.

Some additional Tox tweaks

---

eos/saveddata/fit.py

Fix command burst typo for target painters

---

README.md

We worked hard for it. :)
@blitzmann this is ready to be merged.

Add Travis Icon

---

gui/builtinPreferenceViews/pyfaStatViewPreferences.py
gui/builtinStatsViews/outgoingViewMinimal.py
gui/statsPane.py
service/settings.py

Quick PR to properly merge the new pane into the Preferences PR.
@blitzmann this is ready to merge.

Changes required to implement the remote reps pane

---

service/character.py
service/fit.py
service/network.py
service/port.py
service/prefetch.py
service/price.py
service/server.py
service/update.py

Just a quick PR to add some more logging, especially on the various import/export to hopefully help catch issues users are having when importing/exporting.
@blitzmann this is ready to merge

Add additional logging to services

---

gui/builtinViews/fittingView.py

Fix for first low slot drag and drop

---

gui/shipBrowser.py

Just a quick usability update suggested by a corpmate.
Works from context menu and on middle click - like a web browser

Add option to open fit in new tab

---

eos/config.py
eos/effects/tractorbeamcan.py
gui/builtinPreferenceViews/pyfaStatViewPreferences.py
gui/builtinStatsViews/targetingMiscViewFull.py
service/port.py
service/settings.py

Spelling Is Hurd

---

eos/gamedata.py
eos/saveddata/module.py
gui/builtinViews/fittingView.py

Fixes case that would generate a exception on the first fit calc (would trigger logging dumps for users).  Also  clean up a bunch of unnecessary try/exceptions, and some logging improvements.
@blitzmann this is ready to merge.

Quick Eos cleanup and logging fix

---

gui/builtinPreferenceViews/pyfaStatViewPreferences.py
gui/builtinStatsViews/__init__.py
gui/builtinStatsViews/outgoingViewMinimal.py
gui/statsView.py

Fix the view. Not sure why it broke (it was working at one point).

Fix outgoingMinimal view

---

gui/graphFrame.py

@blitzmann not sure what happened here with imports.  This is an absolute mess, from an import perspective.  There must have been a bad merge or force push at some point, because it's basically half like the branch I have where I fixed it, and half what it was originally. :(
Anyway, cleaned that up.
Apparently stacktraces can be generated deep within matplotlib, and we were only catching import errors.  Now we'll catch everything and bubble up a critical exception (to trip the FingersCrossedHandler).  Normal import errors will simply continue to be a warning and won't trip a log dump.

Hotfix - Matplotlib import

---

gui/builtinViews/fittingView.py
gui/shipBrowser.py
service/fit.py

Since we repeatedly get reports of issues from users, but can't replicate them, I went ahed and added a ton of logging to the Fit service.  Not all of the log messages capture as much data as I'd like (I got lazy about halfway through), but it'll shed a _lot_ of light when users are having stacktraces or hangups.

Fit service logging

---

service/market.py
tests/test_modules/test_service/test_fit.py

Fix for #1061

---

gui/builtinStatsViews/rechargeViewFull.py

See #686
https://gyazo.com/b2bda98ff63a5f6a7419169f916aa626

Switch units in recharge pane based on effective HP toggle

---

eos/db/saveddata/databaseRepair.py

Column `Amount` didn't exist... not sure why we didn't get a database error
edit: we did get error, by the logger didn't get it, or something. Anyway, we return `None` and don't check for this or know what to do with it. Should be safe now.

Fix for #1091

---

eos/saveddata/fit.py

The command fit state PR (#1074) did not include this change, which takes the state into consideration during calcs. Think I forgot to push this commit along with that branch, and it got reset somewhere.

Respect command fit state

---

gui/builtinContextMenus/openFit.py

Very simple and easy QOL change. Self explanatory.

Extend "Open Fit In Context Menu" option for command fits.

---

eos/saveddata/fit.py

Some quick cleanup of logging and shtuff

Some quick cleanup of logging and shtuff

---

eos/db/saveddata/queries.py
gui/builtinContextMenus/priceClear.py
gui/builtinPreferenceViews/pyfaDatabasePreferences.py
gui/utils/helpers_wxPython.py

For #1119, includes work by @Ebag333

"Delete all" buttons for Prices, Target Resists, Damage Profiles

---

_development/helpers_fits.py
tests/test_modules/test_eos/test_saveddata/test_fit_2.py

Tests for eos\saveddata\fit.

---

gui/builtinPreferenceViews/pyfaDatabasePreferences.py
gui/builtinPreferenceViews/pyfaGeneralPreferences.py
gui/marketBrowser.py
service/fit.py

Implements #1122, see that for details

Add a small delay on key down for market search

---

.appveyor.yml
dist_assets/win/pyfa.spec
dist_assets/win/pyfa_debug.spec
requirements_build_windows.txt
setup.py

Picks a few things from dev into master

Appveyor tweaks

---

eos/effects/modulebonusfightersupportunit.py

These fighter modifiers are supposed to be in their own pen-group.

Fix for #1128

---

gui/builtinContextMenus/changeAffectingSkills.py

Request from https://forums.eveonline.com/default.aspx?g=posts&m=6910831#post6910831

Add affecting skills context menu to drones and fighters

---

eos/saveddata/drone.py
eos/saveddata/fit.py
gui/builtinViewColumns/misc.py

Quick fixes for #1132 and #1133

Drone bugs

---

eos/saveddata/fit.py

Remote Ancil Bug

---

eos/effects/miningforemanburstbonusorecapital2.py
eos/effects/shieldcommandburstbonusorecapital3.py

Capital Industrial skill was applying to incorrect attribute for Rorqual's command burst bonuses

Fix for #1137

---

config.py
gui/mainFrame.py

Release 1.29.0

---

eos/saveddata/fit.py
gui/builtinContextMenus/commandFits.py
gui/builtinContextMenus/tabbedFits.py
gui/builtinViews/fittingView.py
gui/graphFrame.py
gui/mainFrame.py
service/fit.py
service/port.py

Thanks to Ebag333 for the fix :)

Fix issues revolving around unicode fit names

---

eos/saveddata/character.py
gui/characterEditor.py
gui/characterSelection.py
gui/mainFrame.py

Character skill revert error, and possible fix for an issue described on the eve-o forums (Skill.character should now always be defined).

Various character fixes

---

eos/saveddata/character.py
service/character.py

Thanks to @Ebag333 for the quick diagnoses and fix :D

EVEMon import fix

---

eos/saveddata/fit.py

Fix issue with calculateSustainableTank not considering remote ancil modules (from https://forums.eveonline.com/default.aspx?g=posts&m=6948134#post6948134)

Add remote ancil modules to the sustained cap stuff

---

gui/builtinViews/fittingView.py

Don't process removeModule if ctrl / cmd key is active

---

gui/builtinViewColumns/baseName.py
gui/builtinViews/fittingView.py
gui/projectedView.py
gui/shipBrowser.py
service/fit.py

more fixes for fit deletion stuff (#1176) along with more logging
kinda of a blind effort at this point, need to really look into the process of fit deletions in general

Fit deletion issues

---

config.py
eos/db/saveddata/queries.py
gui/characterEditor.py
gui/crestFittings.py
service/fit.py

17-06-2017 WiP changes pre-release version PYFA request :)
Tengu
https://docs.google.com/document/d/11cEPxqqQ5uBHFaXmv_FgbKzcIJSQ0o_xEDPL_UOz7xI/edit
Proteus
https://docs.google.com/document/d/1q0HSnCO8ZF5L_VdoIqPRBPqexbWAj2LPWJhhRh7BALk/edit
Loki
https://docs.google.com/document/d/1DD5fLwEkXjx1DeJh9TqIh97VD37Po7R0EqMTsAGfsRk/edit
Legion
https://docs.google.com/document/d/1vGGgy84Sut0FOX1U18Npu54wShQUgnTkUCdVKyW914A/edit
Official CCP focus groups log
https://focusgrouplogs.tech.ccp.is

T3C rebalance pre-release version request

---

gui/builtinContextMenus/implantSets.py
gui/characterEditor.py

Fixes the implant editor on the character to point to the new EntityEditor stuff... this must have been broken for months >.<

Fix setting implant set for character implants

---

eos/gamedata.py

Fix override importing

---

eos/effects/subsystembonusamarrdefensive2scanprobestrength.py

Add missing effect

---

gui/builtinContextMenus/amount.py
gui/builtinContextMenus/itemRemove.py

Use unicode string to prevent non-ASCII ship names from causing error

---

.gitignore
gui/characterEditor.py
gui/utils/roman.py

Needs code review - I'm a python and git developer noob.
Added imports of "re" and "roman" modules to characterEditor.py too, not sure if these need adding someplace else so pyfa builds fine

Character Editor: accept skill plans in Roman numerals too

---

gui/builtinContextMenus/amount.py

Should address #1399 (once merged into 2.x branch)

Redesign amount modal

---

gui/builtinAdditionPanes/projectedView.py
gui/characterSelection.py

Also renames "Export" to "Copy" in the fitting window character selection to better convey that it's copying to clipboard rather than exporting to file

Add ability to drag modules from fitting window to projected pane (#1397)

---

service/character.py

Resolves issue #1453 with xmlparser.ParseFile(file) wanting bytes.

Resolves issue #1453 with xmlparser.ParseFile(file) wanting bytes.

---

eos/effects/doomsdayaoebubble.py
eos/effects/structuremissileguidanceenhancer.py
eos/effects/structurewarpscrambleblockmwdwithnpceffect.py
eos/effects/warpdisruptsphere.py
eos/effects/warpscrambleblockmwdwithnpceffect.py

Added the code to turn off MJDs for various modules. Also ensure they operate correctly depending on script loaded. Various other corrections to operation. See Issue #1456 for further details.

Redefine operation of numerous effects.

---

gui/builtinPreferenceViews/pyfaNetworkPreferences.py
service/network.py

I didn't test it yet (Pyfa crashes when trying to add a new character - Issue #1468 )
Coded according to documentation.
Will try to test in in WIndows later...
In attempt to fix #1465

Apply proxy settings for requests library. Fixes #1465

---

eos/saveddata/module.py

Make appropriate modification to instances of this attribute
name in code.

Attribute disallowRepeatingAction has been renamed.

---

eos/effects/usemissiles.py
eos/saveddata/module.py

Fix bomb dps and void bombs cap/sec. This addresses issue #1488.

Bomb Launcher Problems Issue#1488

---

eos/saveddata/module.py

Fix cap use for non repeatable modules.

---

service/jargon/header.yaml
service/jargon/loader.py

This PR addresses https://github.com/pyfa-org/Pyfa/issues/1533

Improve user experience customizing jargon.yaml

---

gui/esiFittings.py

Skip fits for unknown ships in "Browse EVE Fittings"

---

eos/saveddata/character.py
service/character.py

Address Issue where evemon xml was not being imported

---

dist_assets/mac/pyfa.spec

This should help pyfa to look better on macOS 📺

Make pyfa retina ready

---

service/port.py

Fix for #1674, should fix both issues mentioned.

Bug fix to set implantLocation when importing fits

---

service/fit.py

#1690 and #1695.  Retrying pull request after running tox tests and fixing other pull issues.

Bug/1695, Bug/1690

---

gui/builtinViewColumns/price.py
service/price.py

This should address #1706  
Due to some refactoring last year, the callbacks driving the price column "updating" stopped working. This fix should fix the heart of the issue until a better pricing solution can be identified and worked out (see #1709 for further discussion)
@feyyd please review as well :)
---
This also brings back the various indicators for the price, such as "currently fetching"
and "oh shit something went wrong"

Price callback fix

---

scripts/jsonToSql.py

Make sure small abyssal nos has a type name (bad eve data)

---

gui/chrome_tabs.py

Before:
After:
(You might need to view these images on a Retina screen to see the difference).

The text drawn in chrome_tabs is now crisp on Retina screens

---

gui/errorDialog.py

Pretty simple update, this adds more information to the error dialog output

Add pyfa and eve data version to error dialog

---

eos/saveddata/fit.py

Fix for localized fliament abyssal effect

---

gui/bitmap_loader.py

This should solve the problem for all images loaded with getBitmap(). You can test it by grabbing CCP's high-res images from https://developers.eveonline.com/resource/resources and adding a 2x version of whatever icon/image you find.
Before:
After:
Code that uses getImage(), unfortunately, must either be converted to use getBitmap() (the preferable way), or carry the scaling factor up until it actually draws the image, and downscale it there (with this patch, getImage() will return a prescaled-down-to-regular-size version of the 2x image, so code using it shouldn't be affected).

BitmapLoader.getBitmap will now load a @2x (or whatever the main window's content scale is) bitmap, if one is available.

---

eos/graph/fitDps.py

Don't include non active fighters in dps graph

---

gui/fitCommands/calc/fitReplaceModule.py

Move caching of old module into Do function. Having it in `change_module` causes it to run even with the Undo command, whch causes funkiness
#1806

Attempt to save the charge when changing module variations.

---

gui/builtinContextMenus/fillWithModule.py
gui/contextMenu.py
gui/fitCommands/__init__.py
gui/fitCommands/guiFillWithModule.py

PR for this issue #1779
I wondered if I needed to make a new FitFillWithModuleCommand, but using FitAddModuleCommand seems to work well enough (including the undo). Tell me if you want something else or if you have comments :)

Right click option to fill slots with a module

---

config.py
eos/gamedata.py
gui/builtinMarketBrowser/itemView.py
gui/builtinPreferenceViews/pyfaGeneralPreferences.py
gui/builtinViews/fittingView.py
gui/display.py

attempts to resolve #1839 
my first python code ;) let's see how your check tools treat it

make the item list colour per slot if colorFitBySlot set

---

gui/builtinContextMenus/damagePattern.py
gui/builtinContextMenus/factorReload.py
gui/builtinStatsViews/firepowerViewFull.py
gui/builtinStatsViews/resistancesViewFull.py
gui/contextMenu.py
gui/statsPane.py
gui/toggle_panel.py

Stats menu indicators

---

service/character.py

Include skill prerequisites for applied implants and boosters in fit skill check.

Applied implant and booster skill check

---

service/port/efs.py

Fix for a bug that popped up with v2.9.4.

Fix for EFS exports with ASBs.

---

CONTRIBUTING.md
README.md

It wasn't very clear how to set up project when I decided to contribute myself, so decided as a first task to create clear and simple guide. 
- Written instructions how to set up the project in CLI.
- Added new guide to set project up using PyCharm/IntelliJ. 
- Since it took too much space - separated in into separate file *contributing.md*.

Re-written in much greater detail instructions how to set up the project

---

eos/saveddata/damagePattern.py
gui/mainFrame.py
gui/mainMenuBar.py
gui/utils/exportStats.py

Added a menu item in the "Edit" menu, which copies a compact form of the currently selected fit stats to the clipboard.

Implemented copying the currently open fit stats to the clipboard.

---

CONTRIBUTING.md

Well, not much to say. Though not all tests are working atm lol

Added instructions to run tests for the project

---

eos/utils/stats.py
tests/test_modules/test_eos/test_utils/test_stats.py

As discussed, added central place to retrieve string list of damage types and ehp types.
Also added tests that cover new methods and refactoring of the __repr__ method
Please, take a look.

Added central place to get damage types and ehp sources. Added tests

---

gui/copySelectDialog.py

Not sure that it will fix the problem since I don't see the reason for it in the code in the first place. But at least it should fix that no copyFormat variable is defines

Possible fix for #2084

---

gui/characterEditor.py
gui/esiFittings.py

and add button to retrieve all chars directly linked to existing sso characters.
I just ran into this issue today and was annoyed enough to just fix it. Let me know if you see any issues with this patch.

Regarding #2045: automatically create a character for a new sso character 

---

config.py
gui/builtinShipBrowser/navigationPanel.py
gui/builtinStatsViews/resistancesViewFull.py
gui/characterEditor.py
gui/chrome_tabs.py
gui/multiSwitch.py
gui/propertyEditor.py
gui/ssoLogin.py
locale/README.md
locale/zh_CN/LC_MESSAGES/lang.po

Though currently add more translation is not the priority, it's a good way to find out which part of GUI still need annotate.
Currently zh_CN translation is sitting at 292/314 (92%), with these components still need more work:
* Preferences window - completely not translated
* Graph window - completely not translated
* Fit table high/med/low/rig slot names
* Various column names
Edit: of course there is a grammar error.

I18n: more zh_CN translations and a better locale/README.md

---

gui/builtinAdditionPanes/commandView.py
gui/builtinAdditionPanes/fighterView.py
gui/builtinAdditionPanes/implantView.py
gui/builtinAdditionPanes/projectedView.py
gui/builtinContextMenus/skillAffectors.py
gui/builtinMarketBrowser/marketTree.py
gui/characterEditor.py
gui/copySelectDialog.py
gui/esiFittings.py
locale/README.md
locale/zh_CN/LC_MESSAGES/lang.po
service/character.py
service/port/dna.py
service/port/eft.py
service/port/multibuy.py

It seems that the default output from GNU gettext is sorted by file, or not sorted at all. Currently I'm using `-s` option for various GNU gettext tools to sort lang.po by msgid.

i18n: sort zh_CN translation, more zh_CN translation

---

locale/README.md

My OCD made me do this, it was bothering me. 👋 Told you I'd contribute to this one day.

Translating Typo To English

---

gui/builtinContextMenus/fitSystemSecurity.py
gui/builtinContextMenus/shipModeChange.py
gui/builtinContextMenus/targetProfile/switcher.py
gui/builtinShipBrowser/fitItem.py
locale/zh_CN/LC_MESSAGES/lang.po

In current stage, I think Chinese translation is somewhat stable. Instead having everyone running from source, could we have alpha release of localized pyfa, and let people try it out?

i18n: more translation for zh_CN

---

db_update.py

As described in [this comment](https://github.com/pyfa-org/Pyfa/pull/2202#issuecomment-652857272), this PR fixes lots of issues caused by returning partial data.

i18n: return compiled_data in _readData

---

graphs/data/fitCapacitor/graph.py
graphs/data/fitDamageStats/graph.py
graphs/data/fitEwarStats/graph.py
graphs/data/fitLockTime/graph.py
graphs/data/fitMobility/graph.py
graphs/data/fitRemoteReps/graph.py
graphs/data/fitShieldRegen/graph.py
graphs/data/fitWarpTime/graph.py
graphs/gui/ctrlPanel.py
graphs/gui/frame.py
graphs/gui/lists.py
graphs/style.py
gui/builtinContextMenus/graphDmgDroneMode.py
gui/builtinContextMenus/targetProfile/adder.py
locale/lang.pot
locale/zh_CN/LC_MESSAGES/lang.po

The last major piece of GUI translation is Graph window  (I think). The translation is ready, but the graph panel produced by `matplotlib` still has font issue (can't display Chinese characters). Which is annoying, but the issue does not block string annotation and translation.
I'm not sure about the workflow with Crowdin, so I kept `lang.pot` and Chinese translation in a staging branch `i18n-staging`  😄 .

i18n: string annotation for graph panels

---

eos/saveddata/damagePattern.py
eos/saveddata/targetProfile.py

Added new target and damage profiles for invasion drifters, rogue drones and sleepers.

---

README.md

Update README for self-contained Linux AppImage.

---

service/port/efs.py

ADD: Added Remote Capacitor Transmitters!

Issue 2425 : Remote Capacitor Transmitters not being correctly written in EFS format 

---

gui/utils/exportHtml.py

Fixed Key Error when export.
https://github.com/pyfa-org/Pyfa/issues/2595

Fix exportHtml.py

---

gui/utils/exportHtml.py

Searchable exportHtml.py

---

gui/builtinContextMenus/__init__.py
gui/builtinContextMenus/cargoFill.py

This pr adds a new context menu item that allows users to automatically fill their ships cargo with the given item

Add "Fill cargo" feature to item context menu
